language: node_js
dist: trusty
sudo: required
node_js:
  - "9"
  - "8"
  - "7"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
addons:
  chrome: stable
install:
  - yarn install
script:
  - env
  - npm run test
  - npm run build
